In [18]:
import numpy as np
import random

### Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) Матрица не определена (кол-во столбцов матрицы A не совпадает с кол-вом строк матрицы B)

б) Результирующая матрица: 2 х 3

в) Результирующая матрица: 8 х 8

г) Результирующая матрица: 4 х 4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [2]:
A = np.array([
    [1,-2],
    [3, 0]
])

B = np.array([
    [4,-1],
    [0, 5]
])

In [5]:
print(A + B)

[[ 5 -3]
 [ 3  5]]


In [6]:
print(np.dot(A, B))

[[  4 -11]
 [ 12  -3]]


In [7]:
print(np.dot(B, A))

[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [8]:
A = np.array([
    [1, 7],
    [3,-6]
])

B = np.array([
    [0, 5],
    [2,-1]
])

C = np.array([
    [2,-4],
    [1, 1]
])

In [9]:
print(3*A - 2*B + 4*C)

[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [10]:
A = np.array([
    [4, 1],
    [5,-2],
    [2, 3]
])

In [11]:
print(np.dot(A, A.T))

[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [12]:
print(np.dot(A.T, A))

[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [147]:
def my_func(matrix_1: np.array, matrix_2: np.array):
    
    result = [[0 for x in range(len(matrix_1))] for y in range(len(matrix_2[0]))]
    
    assert len(matrix_1[0]) == len(matrix_2), 'Матрицы не могут быть перемножены'
    
    for i in range(len(matrix_1)):
        for j in range(len(matrix_2[0])):
            for k in range(len(matrix_1[0])):
                result[i][j] += matrix_1[i][k] * matrix_2[k][j]
                
    return result

In [148]:
A = np.array([
    [1,-2, 1],
    [3, 0, 1],
    [4, -5, 2]
])

B = np.array([
    [4,-1, 2],
    [0, 5, 4],
    [1, 2, 6]
])

In [149]:
my_func(A, B)

[[5, -9, 0], [13, -1, 12], [18, -25, 0]]

### Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [19]:
x = random.randint(0, 100)

A = np.array([
    [np.sin(x), -np.cos(x)],
    [np.cos(x),  np.sin(x)]
])

In [20]:
round(np.linalg.det(A))

1

In [22]:
B = np.array([
    [4, 2, 3],
    [0, 5, 1],
    [0, 0, 9]
])

In [23]:
np.linalg.det(B)

180.0

In [24]:
C = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [27]:
round(np.linalg.det(C))

0

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

a) При возведении матрицы в степень, определитель получит такую же степень. Ответ 16.

б) Определители транспонированной матрицы равен определителю исходной. Ответ 4.

в) При умножении матрицы на число, определитель матрицы будет умножен на то же число в степени, равной количеству строк. Ответ 4*2^3 = 32.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

По определению матрица называется вырожденной, если ее определитель равен нулю.

In [28]:
A = np.array([
    [-2,   7, -3],
    [ 4, -14,  6],
    [-3,   7, 13]
])

In [29]:
round(np.linalg.det(A))

0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [30]:
A = np.array([
    [1, 2, 3],
    [1, 1, 1],
    [2, 3, 4]
])

B = np.array([
    [0, 0, 2, 1],
    [0, 0, 2, 2],
    [0, 0, 4, 3],
    [2, 3, 5, 6]
])

In [31]:
np.linalg.matrix_rank(A)

2

In [32]:
np.linalg.matrix_rank(B)

3