In [12]:
import numpy as np
from numpy.linalg import norm
np.set_printoptions(precision=2, suppress=True)

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [4]:
A = np.array([
    [1,  2, 0],
    [0,  0, 5],
    [3, -4, 2],
    [1,  6, 5],
    [0,  1, 0]
])

In [8]:
U, s, W = np.linalg.svd(A)

V = W.T
print(f'U:\n{U}\n')
print(f's:\n{s}\n')
print(f'Матрица V^T:\n{W}\n')
print(f'Матрица V:\n{V}')

U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]

s:
[8.82 6.14 2.53]

Матрица V^T:
[[ 0.07  0.72  0.69]
 [-0.37  0.67 -0.65]
 [-0.93 -0.21  0.31]]

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [9]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [10]:
# Проверка
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [18]:
print(f'Евклидова норма матрицы А:\n{norm(A, ord=2)}')

Евклидова норма матрицы А:
8.824868854820444


In [19]:
print(f'Норма Фробениуса матрицы А:\n{norm(A)}')

Норма Фробениуса матрицы А:
11.045361017187261
